### ISSUE TITLE
bib-Datei im falschen Dateibaum

### ISSUE THREAD

**Issue by wehro** [dante-ev/dtk-bibliography#14]
In einer TeX-Live-Installation befindet sich die Datei `dtk-bibliography.bib` zur Zeit im `doc`-Baum. Dort wird sie von `kpsewhich` nicht gefunden.
Damit der Befehl `\addbibresource{dtk-bibliography.bib}` funktioniert, müsste sie in den `bibtex`-Baum verschoben werden.
Meines Wissens lässt sich dies beim CTAN-Upload nicht steuern. Man müsste direkt an die TeX-Live-Betreuer herantreten.

**Comment by UweZiegenhagen** [comment]
Has been fixed
