### ISSUE TITLE
Dubletten

### ISSUE THREAD

**Issue by wehro** [dante-ev/dtk-bibliography#15]
Die Einträge mit den Schlüsseln `dtk22.1:hilbricht` und `dtk22.1:ramm` sind doppelt in der Bibliographie vorhanden. Dies führt bei deren Einbindung zu Biber-Warnungen.

**Comment by UweZiegenhagen** [comment]
Danke, kümmere ich mich drum.

**Comment by UweZiegenhagen** [comment]
In der Bib-Datei angepasst.
