### ISSUE TITLE
LaTeX-Logo

### ISSUE THREAD

**Issue by wehro** [dante-ev/dtk-bibliography#16]
In den Artikeltiteln ist das LaTeX-Logo uneinheitlich formatiert. Meist wird `\LaTeX`, `\LuaLaTeX` etc. verwendet, es gibt aber auch Einträge, wo der Befehlsstrich fehlt, z. B. `dtk19.3:entenmann:isomathe`.

**Comment by UweZiegenhagen** [comment]
Danke, kümmere ich mich drum,

**Comment by UweZiegenhagen** [comment]
Habe mit der Anpassung begonnen, wird Schritt für Schritt umgestellt.
