### ISSUE TITLE
Falscher Titel

### ISSUE THREAD

**Issue by wehro** [dante-ev/dtk-bibliography#18]
Der Eintrag `dtk23.1:wehr:schulphysik` hat einen falschen Titel.

**Comment by UweZiegenhagen** [comment]
Welcher ist denn richtig? Ich hab die DTK leider gerade nicht zur Hand

**Comment by wehro** [comment]
`\LaTeX\ und Schulphysik 1: Größen und Einheiten`

**Comment by UweZiegenhagen** [comment]
Ist im Git gefixt, im CTAN Paket erfolgt der Fix mit DTK 3/23
