### ISSUE TITLE
Filter

### ISSUE THREAD

**Issue by UweZiegenhagen** [dante-ev/dtk-bibliography#6]
Aktuell taucht das Grußwort der DTK 01/2017 in beiden Bibliografien auf. Soll das so sein oder sollten die Filter/Keywords so sein, dass die Grußworte nur in einem Teil auftauchen?

**Comment by sieversMartin** [comment]
Das war nur ein erster Test. Wir müssen überlegen, was überhaupt sinnvoll ist.
Wonach möchte man ggf. filtern?
