### ISSUE TITLE
Neuer Key "license"

### ISSUE THREAD

**Issue by rolfn** [dante-ev/dtk-bibliography#9]
Es wäre nützlich, in der Bibliografie einen neuen Key "license" bei Bedarf zu verwenden. Im Heft 1/2019 wird beispielweise ein Artikel mit expliziter Lizenzangabe (im Randbereich) erscheinen:
```
...
license={CC-BY-NC-SA},
...
```
Besondere Änderungen sind vorerst nicht nötig. Damit Lizenz-Einträge später auch in der PDF-Datei auftauchen, muss allerdings der neue Key dem BibLaTeX-Biber-Ablauf bekannt gemacht werden.

**Comment by UweZiegenhagen** [comment]
Danke für den Hinweise, nehme ich dann mit auf. Kannst Du den Code für den neuen Key bereitstellen? Ich kenn mich damit nicht gut aus.
